--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/cooldogedev/EconAPIToBE
build-by-default: true
branches:
- main
projects:
  EconAPIToBE:
    path: ""
    libs:
      - src: cooldogedev/libSQL/libSQL
        version: ^0.1.0
...
